seed_everything: 42

model:
  class_path: "src.models.smp.SMPMulticlassSegmentationModel"
  init_args:
    architecture: "Segformer"
    backbone: "mit_b2"
    model_opts:
      encoder_weights: imagenet
      in_channels: 3
    num_classes: 2
    ignore_index: &ignore_index -100
    lr: 1e-4
    wd: 0.01
    b1: 0.9
    b2: 0.95
    loss: "LovaszLoss"
    loss_opts:
      mode: "multiclass"
      ignore_index: *ignore_index
      from_logits: true
    class_names:
      - bg
      - seagrass

data:
  class_path: "src.data.DataModule"
  init_args:
    train_chip_dir: "/mnt/class_data/sdalgarno/prototype_frac_25/chips_1024/train"
    val_chip_dir: "/mnt/class_data/sdalgarno/prototype_frac_25/chips_1024/val"
    test_chip_dir: "/mnt/class_data/sdalgarno/prototype_frac_25/chips_1024/test"
    batch_size: 6
    num_workers: 16
    pin_memory: true
    persistent_workers: true
    train_transforms:
      __version__: 2.0.9
      transform:
        __class_fullname__: Compose
        additional_targets: {}
        bbox_params: null
        is_check_shapes: true
        keypoint_params: null
        p: 1
        seed: null
        transforms:
          - __class_fullname__: D4
            p: 1.0
          - __class_fullname__: RandomBrightnessContrast
            brightness_by_max: true
            brightness_limit:
              - -0.1
              - 0.1
            contrast_limit:
              - -0.1
              - 0.1
            ensure_safe_range: false
            p: 0.6
          - __class_fullname__: OneOf
            p: 0.4
            transforms:
              - __class_fullname__: GaussNoise
                mean_range:
                  - 0.0
                  - 0.0
                noise_scale_factor: 1.0
                p: 1.0
                per_channel: true
                std_range:
                  - 0.02
                  - 0.044
              - __class_fullname__: ISONoise
                color_shift:
                  - 0.01
                  - 0.05
                intensity:
                  - 0.1
                  - 0.2
                p: 1.0
          - __class_fullname__: OneOf
            p: 0.4
            transforms:
              - __class_fullname__: MotionBlur
                allow_shifted: true
                angle_range:
                  - 0.0
                  - 360.0
                blur_limit:
                  - 3
                  - 7
                direction_range:
                  - -1.0
                  - 1.0
                p: 1.0
              - __class_fullname__: MedianBlur
                blur_limit:
                  - 3
                  - 7
                p: 1.0
              - __class_fullname__: GaussianBlur
                blur_limit:
                  - 0
                  - 0
                p: 1.0
                sigma_limit:
                  - 0.5
                  - 3.0
          - __class_fullname__: Affine
            balanced_scale: false
            border_mode: 0
            fill: 0.0
            fill_mask: 0.0
            fit_output: false
            interpolation: 1
            keep_ratio: true
            mask_interpolation: 0
            p: 0.5
            rotate:
              - 0.0
              - 0.0
            rotate_method: largest_box
            scale:
              x:
                - 0.8
                - 1.2
              y:
                - 0.8
                - 1.2
            shear:
              x:
                - 0.0
                - 0.0
              y:
                - 0.0
                - 0.0
            translate_percent:
              x:
                - 0.0
                - 0.0
              y:
                - 0.0
                - 0.0
            translate_px: null
          - __class_fullname__: CLAHE
            clip_limit:
              - 1.0
              - 4.0
            p: 0.3
            tile_grid_size:
              - 8
              - 8
          - __class_fullname__: HueSaturationValue
            hue_shift_limit:
              - -10.0
              - 10.0
            p: 0.5
            sat_shift_limit:
              - -15.0
              - 15.0
            val_shift_limit:
              - -15.0
              - 15.0
          - __class_fullname__: Normalize
            max_pixel_value: 255.0
            mean:
              - 0.485
              - 0.456
              - 0.406
            normalization: standard
            p: 1.0
            std:
              - 0.229
              - 0.224
              - 0.225
          - __class_fullname__: ToTensorV2
            p: 1.0
            transpose_mask: false
    test_transforms:
      __version__: 2.0.9
      transform:
        __class_fullname__: Compose
        additional_targets: {}
        bbox_params: null
        is_check_shapes: true
        keypoint_params: null
        p: 1
        seed: null
        transforms:
          - __class_fullname__: Normalize
            max_pixel_value: 255.0
            mean:
              - 0.485
              - 0.456
              - 0.406
            normalization: standard
            p: 1.0
            std:
              - 0.229
              - 0.224
              - 0.225
          - __class_fullname__: ToTensorV2
            p: 1.0
            transpose_mask: false

trainer:
  accelerator: auto
  devices: auto
  precision: bf16-mixed
  log_every_n_steps: 20
  max_epochs: 100
  accumulate_grad_batches: 8
  gradient_clip_val: 0.5
  check_val_every_n_epoch: 5
  detect_anomaly: false
  default_root_dir: checkpoints
  fast_dev_run: False
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        entity: sebdalgarno-poisson-consulting
        project: seagrass-rgb
        name: segformer_domain_aug
        group: augmentation-experiment
        log_model: true
        tags:
          - seagrass
          - augmentation-experiment
          - segformer
          - domain-aug
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        auto_insert_metric_name: False
        filename: segformer_domain_aug_epoch-{epoch:02d}_val-iou-{val/iou_epoch:.4f}
        monitor: val/iou_epoch
        mode: max
        save_last: True
        save_top_k: 2
        save_weights_only: True
        verbose: True
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val/iou_epoch
        mode: max
        patience: 20
        min_delta: 0.002
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  plugins:
    - class_path: lightning.pytorch.plugins.io.AsyncCheckpointIO
