# lightning.pytorch==2.6.0
seed_everything: 42
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: bf16-mixed
  logger:
  - class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: unetpp_resnet34
      save_dir: .
      version: null
      offline: false
      dir: null
      id: null
      anonymous: null
      project: seagrass-rgb
      log_model: true
      experiment: null
      prefix: ''
      checkpoint_name: null
      add_file_policy: mutable
      entity: sebdalgarno-poisson-consulting
      notes: null
      tags:
      - seagrass
      - baseline_comparison
      config: null
      config_exclude_keys: null
      config_include_keys: null
      allow_val_change: null
      group: baseline_comparison
      job_type: null
      mode: null
      force: null
      reinit: null
      resume: null
      resume_from: null
      fork_from: null
      save_code: null
      tensorboard: null
      sync_tensorboard: null
      monitor_gym: null
      settings: null
  callbacks:
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: null
      filename: seagrass_rgb_unetpp_resnet34_epoch-{epoch:02d}_val-iou-{val/iou_epoch:.4f}
      monitor: val/iou_epoch
      verbose: true
      save_last: true
      save_top_k: 2
      save_on_exception: false
      save_weights_only: true
      mode: max
      auto_insert_metric_name: false
      every_n_train_steps: null
      train_time_interval: null
      every_n_epochs: null
      save_on_train_epoch_end: null
      enable_version_counter: true
  - class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      monitor: val/iou_epoch
      min_delta: 0.0
      patience: 10
      verbose: false
      mode: max
      strict: true
      check_finite: true
      stopping_threshold: null
      divergence_threshold: null
      check_on_train_epoch_end: null
      log_rank_zero_only: false
  - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    init_args:
      logging_interval: step
      log_momentum: false
      log_weight_decay: false
  fast_dev_run: false
  max_epochs: 100
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: 20
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 4
  gradient_clip_val: 0.5
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins:
  - class_path: lightning.pytorch.plugins.io.AsyncCheckpointIO
    init_args:
      checkpoint_io: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: checkpoints
  enable_autolog_hparams: true
  model_registry: null
model:
  class_path: src.models.smp.SMPMulticlassSegmentationModel
  init_args:
    class_names:
    - bg
    - seagrass
    architecture: UnetPlusPlus
    backbone: resnet34
    model_opts:
      encoder_weights: imagenet
      in_channels: 3
    loss: LovaszLoss
    loss_opts:
      mode: multiclass
      ignore_index: -100
      from_logits: true
    num_classes: 2
    ignore_index: -100
    lr: 0.0003
    wd: 0.01
    b1: 0.9
    b2: 0.95
    amsgrad: false
    warmup_period: 0.1
    ckpt_path: null
    freeze_backbone: false
data:
  class_path: src.data.DataModule
  init_args:
    train_chip_dir: /mnt/class_data/sdalgarno/prototype/chips/train
    val_chip_dir: /mnt/class_data/sdalgarno/prototype/chips/val
    test_chip_dir: /mnt/class_data/sdalgarno/prototype/chips/test
    batch_size: 8
    num_workers: 8
    pin_memory: true
    persistent_workers: true
    train_transforms:
      __version__: 2.0.9
      transform:
        __class_fullname__: Compose
        additional_targets: {}
        bbox_params: null
        is_check_shapes: true
        keypoint_params: null
        p: 1
        seed: null
        transforms:
        - __class_fullname__: D4
          p: 1.0
        - __class_fullname__: HueSaturationValue
          hue_shift_limit:
          - -15
          - 15
          sat_shift_limit:
          - -25
          - 25
          val_shift_limit:
          - -25
          - 25
          p: 0.6
        - __class_fullname__: RandomBrightnessContrast
          brightness_by_max: true
          brightness_limit:
          - -0.2
          - 0.2
          contrast_limit:
          - -0.2
          - 0.2
          ensure_safe_range: false
          p: 0.5
        - __class_fullname__: RandomGamma
          gamma_limit:
          - 80
          - 120
          p: 0.3
        - __class_fullname__: GaussianBlur
          blur_limit:
          - 3
          - 7
          p: 0.2
        - __class_fullname__: Normalize
          max_pixel_value: 255.0
          mean:
          - 0.485
          - 0.456
          - 0.406
          normalization: standard
          p: 1.0
          std:
          - 0.229
          - 0.224
          - 0.225
        - __class_fullname__: ToTensorV2
          p: 1.0
          transpose_mask: false
    test_transforms:
      __version__: 2.0.9
      transform:
        __class_fullname__: Compose
        additional_targets: {}
        bbox_params: null
        is_check_shapes: true
        keypoint_params: null
        p: 1
        seed: null
        transforms:
        - __class_fullname__: Normalize
          max_pixel_value: 255.0
          mean:
          - 0.485
          - 0.456
          - 0.406
          normalization: standard
          p: 1.0
          std:
          - 0.229
          - 0.224
          - 0.225
        - __class_fullname__: ToTensorV2
          p: 1.0
          transpose_mask: false
optimizer: null
lr_scheduler: null
ckpt_path: null
weights_only: null
