seed_everything: 42

model:
  class_path: "src.models.smp.SMPMulticlassSegmentationModel"
  init_args:
    architecture: "UnetPlusPlus"
    backbone: "resnet34"
    model_opts:
      encoder_weights: imagenet
      in_channels: 3
    num_classes: 2
    ignore_index: &ignore_index -100
    lr: 1e-4
    wd: 0.01
    b1: 0.9
    b2: 0.95
    loss: "LovaszLoss"
    loss_opts:
      mode: "multiclass"
      ignore_index: *ignore_index
      from_logits: true
    class_names:
      - bg
      - seagrass

data:
  class_path: "src.data.DataModule"
  init_args:
    train_chip_dir: "/mnt/class_data/sdalgarno/prototype/chips_1024/train"
    val_chip_dir: "/mnt/class_data/sdalgarno/prototype/chips_1024/val"
    test_chip_dir: "/mnt/class_data/sdalgarno/prototype/chips_1024/test"
    batch_size: 12
    num_workers: 16
    pin_memory: true
    persistent_workers: true
    train_transforms:
      __version__: 2.0.9
      transform:
        __class_fullname__: Compose
        additional_targets: {}
        bbox_params: null
        is_check_shapes: true
        keypoint_params: null
        p: 1
        seed: null
        transforms:
          - __class_fullname__: D4
            p: 1.0
          - __class_fullname__: Normalize
            max_pixel_value: 255.0
            mean:
              - 0.485
              - 0.456
              - 0.406
            normalization: standard
            p: 1.0
            std:
              - 0.229
              - 0.224
              - 0.225
          - __class_fullname__: ToTensorV2
            p: 1.0
            transpose_mask: false
    test_transforms:
      __version__: 2.0.9
      transform:
        __class_fullname__: Compose
        additional_targets: {}
        bbox_params: null
        is_check_shapes: true
        keypoint_params: null
        p: 1
        seed: null
        transforms:
          - __class_fullname__: Normalize
            max_pixel_value: 255.0
            mean:
              - 0.485
              - 0.456
              - 0.406
            normalization: standard
            p: 1.0
            std:
              - 0.229
              - 0.224
              - 0.225
          - __class_fullname__: ToTensorV2
            p: 1.0
            transpose_mask: false

trainer:
  accelerator: auto
  devices: auto
  precision: bf16-mixed
  log_every_n_steps: 20
  max_epochs: 200
  accumulate_grad_batches: 4
  gradient_clip_val: 0.5
  check_val_every_n_epoch: 1
  detect_anomaly: false
  default_root_dir: checkpoints
  fast_dev_run: False
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        entity: sebdalgarno-poisson-consulting
        project: seagrass-rgb
        name: unetpp_resnet34_1024
        group: architecture-experiment
        log_model: true
        tags:
          - seagrass
          - architecture-experiment
          - unetpp
          - resnet34
          - 1024
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        auto_insert_metric_name: False
        filename: unetpp_resnet34_1024_epoch-{epoch:02d}_val-iou-{val/iou_epoch:.4f}
        monitor: val/iou_epoch
        mode: max
        save_last: True
        save_top_k: 2
        save_weights_only: True
        verbose: True
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val/iou_epoch
        mode: max
        patience: 20
        min_delta: 0.002
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  plugins:
    - class_path: lightning.pytorch.plugins.io.AsyncCheckpointIO
